// Langues disponibles, sens d'écriture et textes. Ajouter une langue = ajouter une entrée dans les 3 objets.
export const LOCALES = { fr: 'Français', en: 'English', ar: 'العربية' };
export const DIR = { fr: 'ltr', en: 'ltr', ar: 'rtl' };
export const DICT = {
  fr: { tagline: 'Les conférences, à la demande.', login: 'Connexion', register: 'Créer un compte', logout: 'Déconnexion', account: 'Mon compte', email: 'Email', password: 'Mot de passe (8 caractères min.)', name: 'Nom', submit: 'Valider', role: 'Rôle', hello: 'Bonjour', errInvalid: 'Identifiants invalides', errExists: 'Email déjà utilisé', errGeneric: 'Une erreur est survenue', search: 'Rechercher une conférence…', allCategories: 'Toutes les catégories', noTalks: 'Aucune conférence pour le moment.', free: 'Gratuit', premium: 'Premium', myTalks: 'Mes conférences', addTalk: 'Ajouter une conférence', talkTitle: 'Titre', description: 'Description', speaker: 'Intervenant', language: 'Langue (fr, en, ar…)', category: 'Catégorie', access: 'Accès', videoUrl: 'Lien de la vidéo (YouTube ou Vimeo)', delete: 'Supprimer', errVideo: 'Lien vidéo non reconnu ou champs invalides', noAccess: 'Cette page est réservée aux organisateurs.', publish: 'Publier', source: 'Source de la vidéo', linkMode: 'Lien YouTube / Vimeo', fileMode: 'Fichier vidéo', videoFile: 'Fichier vidéo (MP4 conseillé)', uploading: 'Envoi en cours…', errTooBig: 'Fichier trop volumineux', errUpload: "Échec de l'envoi, réessaie", locked: 'Contenu premium : réservé aux abonnés (bientôt disponible).' },
  en: { tagline: 'Conferences, on demand.', login: 'Log in', register: 'Sign up', logout: 'Log out', account: 'My account', email: 'Email', password: 'Password (8 characters min.)', name: 'Name', submit: 'Submit', role: 'Role', hello: 'Hello', errInvalid: 'Invalid credentials', errExists: 'Email already in use', errGeneric: 'Something went wrong', search: 'Search conferences…', allCategories: 'All categories', noTalks: 'No conferences yet.', free: 'Free', premium: 'Premium', myTalks: 'My conferences', addTalk: 'Add a conference', talkTitle: 'Title', description: 'Description', speaker: 'Speaker', language: 'Language (fr, en, ar…)', category: 'Category', access: 'Access', videoUrl: 'Video link (YouTube or Vimeo)', delete: 'Delete', errVideo: 'Unrecognized video link or invalid fields', noAccess: 'This page is for organizers only.', publish: 'Publish', source: 'Video source', linkMode: 'YouTube / Vimeo link', fileMode: 'Video file', videoFile: 'Video file (MP4 recommended)', uploading: 'Uploading…', errTooBig: 'File too large', errUpload: 'Upload failed, please retry', locked: 'Premium content: subscribers only (coming soon).' },
  ar: { tagline: 'المؤتمرات عند الطلب.', login: 'تسجيل الدخول', register: 'إنشاء حساب', logout: 'تسجيل الخروج', account: 'حسابي', email: 'البريد الإلكتروني', password: 'كلمة المرور (8 أحرف على الأقل)', name: 'الاسم', submit: 'تأكيد', role: 'الدور', hello: 'مرحبًا', errInvalid: 'بيانات الدخول غير صحيحة', errExists: 'البريد الإلكتروني مستخدم بالفعل', errGeneric: 'حدث خطأ', search: 'ابحث عن مؤتمر…', allCategories: 'كل الفئات', noTalks: 'لا توجد مؤتمرات بعد.', free: 'مجاني', premium: 'مميز', myTalks: 'مؤتمراتي', addTalk: 'إضافة مؤتمر', talkTitle: 'العنوان', description: 'الوصف', speaker: 'المتحدث', language: 'اللغة (fr, en, ar…)', category: 'الفئة', access: 'الوصول', videoUrl: 'رابط الفيديو (YouTube أو Vimeo)', delete: 'حذف', errVideo: 'رابط الفيديو غير معروف أو حقول غير صالحة', noAccess: 'هذه الصفحة مخصصة للمنظمين.', publish: 'نشر', source: 'مصدر الفيديو', linkMode: 'رابط YouTube / Vimeo', fileMode: 'ملف فيديو', videoFile: 'ملف فيديو (يُفضّل MP4)', uploading: 'جارٍ الإرسال…', errTooBig: 'الملف كبير جدًا', errUpload: 'فشل الإرسال، أعد المحاولة', locked: 'محتوى مميز: للمشتركين فقط (قريبًا).' },
};
export const getLocale = (value) => (DICT[value] ? value : 'fr');
